function ps = interspeechPlotspec(overallGain)

  dustyPurple = [130/256 96/256 176/256];    
  darkGreen  = [117/256 180/256 82/256];
  darkerGreen  = [112/256 175/256 77/256];     
  mexicanFlagRed = [206/256  17/256  38/256]; 
  mexicanFlagGreen = [  0/256 104/256 71/256];
  gray = [.4 .4 .4];
  ygain = 30 * overallGain;

  % 13 pixels between lines
  % side, feature type, label, ybaseline, ygain, color, linestyle
  % note that y = 0 is at the lower left
  ps  =[{'self'}, {'vo'}, {'Intensity'},  99+89, ygain, dustyPurple, {'-'}; ...  
	{'self'}, {'ph'}, {'Pitch Height'},99+74, ygain, gray, {'-'}; ...
	{'self'}, {'pr'}, {'Pitch Range'}, 99+59, ygain, gray, {'-'}; ...
	{'self'}, {'le'}, {'Lengthening'}, 99+44, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'cr'}, {'Creakiness'},  99+29, ygain, dustyPurple, {'-'}; ...
%	{'self'}, {'pd'}, {'Disalignment'},103+33, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'ap'}, {'Articu. Prec.'},99+14, ygain, gray, {'-'}; ...
		...
	{'inte'}, {'vo'}, {'Intensity'},  89 ygain, darkGreen, {'-'}; ...
	{'inte'}, {'ph'}, {'Pitch Height'},74, ygain, gray, {'-'}; ...
	{'inte'}, {'pr'}, {'Pitch Range'}, 59, ygain, gray, {'-'}; ...
	{'inte'}, {'le'}, {'Lengthening'}, 44, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'cr'}, {'Creakiness'},  29, ygain, darkGreen, {'-'}; ...
%	{'inte'}, {'pd'}, {'Disalignment'},33, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'ap'}, {'Articu. Prec.'},14, ygain, gray, {'-'}; ...
       ];
end
