function ps = midPlotspec(overallGain)

% A specification for how patvis2 should behave.
% derived from stdPlotspec, augmented to handle all features in largest.fss

  dustyPurple = [130/256 96/256 176/256];    
  darkGreen  = [117/256 180/256 82/256];     
  mexicanFlagRed = [206/256  17/256  38/256]; 
  mexicanFlagGreen = [  0/256 104/256 71/256];
  gray = [.4 .4 .4];
  ygain = 25 * overallGain;

  % side, feature type, label, ybaseline, ygain, color, linestyle
  % note that y = 0 is at the lower left
  ps  =[{'self'}, {'vo'}, {'Intensity'},  175, ygain, dustyPurple, {'-'}; ...  
	{'self'}, {'ph'}, {'Pitch Height'},165, ygain, gray, {'-'}; ...
	{'self'}, {'pr'}, {'Pitch Range'}, 155, ygain, gray, {'-'}; ...
	{'self'}, {'pd'}, {'Disalignment'},145, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'le'}, {'Lengthening'}, 135, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'cr'}, {'Creakiness'},  125, ygain, gray, {'-'}; ...
	{'self'}, {'sr'}, {'Energy Flux'}, 115, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'ap'}, {'Articu. Prec.'},105, ygain, dustyPurple, {'-'}; ...
		...
	{'inte'}, {'vo'}, {'Intensity'},  90, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'ph'}, {'Pitch Height'},80, ygain, gray, {'-'}; ...
	{'inte'}, {'pr'}, {'Pitch Range'}, 70, ygain, gray, {'-'}; ...
	{'inte'}, {'pd'}, {'Disalignment'},60, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'le'}, {'Lengthening'}, 50, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'cr'}, {'Creakiness'},  40, ygain, gray, {'-'}; ...
	{'inte'}, {'sr'}, {'Energy Flux'}, 30, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'ap'}, {'Articu. Prec.'},20, ygain, darkGreen, {'-'}; ...
       ];
end
