function ps = midPlotspec()

% A specification for how patvis2 should behave.
% derived from stdPlotspec, augmented to handle all features in largest.fss

  dustyPurple = [130/256 96/256 176/256];    
  darkGreen  = [117/256 180/256 82/256];     
  mexicanFlagRed = [206/256  17/256  38/256]; 
  mexicanFlagGreen = [  0/256 104/256 71/256];
  gray = [.4 .4 .4];

  % side, feature type, label, ybaseline, ygain, color, linestyle
  % note that y = 0 is at the lower left
  ps  =[{'self'}, {'vo'}, {'Intensity'},  175, 25, dustyPurple, {'-'}; ...  
	{'self'}, {'ph'}, {'Pitch Height'},165, 25, gray, {'-'}; ...
	{'self'}, {'pr'}, {'Pitch Range'}, 155, 25, gray, {'-'}; ...
	{'self'}, {'pd'}, {'Disalignment'},145, 25, dustyPurple, {'-'}; ...
	{'self'}, {'le'}, {'Lengthening'}, 135, 25, dustyPurple, {'-'}; ...
	{'self'}, {'cr'}, {'Creakiness'}, 125, 25, gray, {'-'}; ...
	{'self'}, {'sr'}, {'Energy Flux'},115, 25, dustyPurple, {'-'}; ...
	{'self'}, {'ap'}, {'Articu. Prec.'},105, 25, dustyPurple, {'-'}; ...
		...
	{'inte'}, {'vo'}, {'Intensity'},  90, 25, darkGreen, {'-'}; ...
	{'inte'}, {'ph'}, {'Pitch Height'},80, 25, gray, {'-'}; ...
	{'inte'}, {'pr'}, {'Pitch Range'}, 70, 25, gray, {'-'}; ...
	{'inte'}, {'pd'}, {'Disalignment'},60, 25, darkGreen, {'-'}; ...
	{'inte'}, {'le'}, {'Lengthening'}, 50, 25, darkGreen, {'-'}; ...
	{'inte'}, {'cr'}, {'Creakiness'},  40, 25, gray, {'-'}; ...
	{'inte'}, {'sr'}, {'Energy Flux'}, 30, 25, darkGreen, {'-'}; ...
	{'inte'}, {'ap'}, {'Articu. Prec.'},20, 25, darkGreen, {'-'}; ...
       ];
end
