function ps = mono4Plotspec(overallGain)

  dustyPurple = [130/256 96/256 176/256];    
  darkGreen  = [117/256 180/256 82/256];     
  gray = [.4 .4 .4];
  ygain = 25 * overallGain;

  % side, feature type, label, ybaseline, ygain, color, linestyle
  % note that y = 0 is at the lower left
  ps  =[{'self'}, {'vo'}, {'Intensity'},  175, ygain, dustyPurple, {'-'}; ...  
	{'self'}, {'ph'}, {'Pitch Height'},165, ygain, gray, {'-'}; ...
	{'self'}, {'pr'}, {'Pitch Range'}, 155, ygain, gray, {'-'}; ...
	{'self'}, {'pd'}, {'Disalignment'},145, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'le'}, {'Lengthening'}, 135, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'cr'}, {'Creakiness'},  125, ygain, gray, {'-'}; ...
	{'self'}, {'sr'}, {'Energy Flux'}, 115, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'vr'}, {'V-U I. Ratio'},105, ygain, dustyPurple, {'-'}; ...
		...
       ];
end

% patvis2('cluster 1', cluster1center, 'mono4.fss', mono4Plotspec(1), -2400, +2400, '100 clusters with mono4 and temporal*4');
