function ps = mono4Plotspec(overallGain)

  dustyPurple = [130/256 96/256 176/256];    
  darkGreen  = [117/256 180/256 82/256];     
  gray = [.4 .4 .4];
  ygain = 25 * overallGain;

  % side, feature type, label, ybaseline, ygain, color, linestyle
  % note that y = 0 is at the lower left
  ps  =[{'self'}, {'vo'}, {'Intensity'},  115, ygain, dustyPurple, {'-'}; ...  
	{'self'}, {'ph'}, {'Pitch Height'},100, ygain, gray, {'-'}; ...
	{'self'}, {'pr'}, {'Pitch Range'}, 85, ygain, gray, {'-'}; ...
	{'self'}, {'pd'}, {'Disalignment'},70, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'le'}, {'Lengthening'}, 55, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'ap'}, {'Artic. Preci'},  40, ygain, gray, {'-'}; ...
	{'self'}, {'sr'}, {'Energy Flux'}, 25, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'vr'}, {'V-U I. Ratio'},10, ygain, dustyPurple, {'-'}; ...
		...
       ];
end

