function ps = pbookPlotspecFull(overallGain)

  %% displays all features, without compressing pitch highness/lowness (etc) into one line

  dustyPurple = [130/256 96/256 176/256];    
  darkGreen  = [117/256 180/256 82/256];     
  mexicanFlagRed = [206/256  17/256  38/256]; 
  mexicanFlagGreen = [  0/256 104/256 71/256];
  gray = [.4 .4 .4];
  ygain = 25 * overallGain;

  % side, feature type, label, ybaseline, ygain, color, linestyle
  % note that y = 0 is at the lower left
  ps  =[{'self'}, {'vo'}, {'Intensity'},  185, ygain, dustyPurple, {'-'}; ...  
	{'self'}, {'th'}, {'P. Highness'},175, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'tl'}, {'P. Lowness'},165, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'wp'}, {'P. Wideness'}, 155, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'np'}, {'P. Narrowness'}, 145, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'le'}, {'Lengthening'}, 135, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'cr'}, {'Creakiness'},  125, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'pd'}, {'Disalignment'},115, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'en'}, {'Enunciation'},105, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'re'}, {'Reduction'},95, ygain, dustyPurple, {'-'}; ...
		...
	{'inte'}, {'vo'}, {'Intensity'},  80, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'ph'}, {'Pitch Height'},70, ygain, gray, {'-'}; ...
	{'inte'}, {'pr'}, {'Pitch Range'}, 60, ygain, gray, {'-'}; ...
	{'inte'}, {'le'}, {'Lengthening'}, 50, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'cr'}, {'Creakiness'},  40, ygain, gray, {'-'}; ...
	{'inte'}, {'pd'}, {'Disalignment'},30, ygain, darkGreen, {'-'}; ...
	{'self'}, {'ap'}, {'Articu. Prec.'},20, ygain, darkGreen, {'-'}; ...

       ];
end
