function ps = mono4Plotspec(overallGain)

  dustyPurple = [130/256 96/256 176/256];    
  darkGreen  = [117/256 180/256 82/256];     
  mexicanFlagRed = [206/256  17/256  38/256]; 
  mexicanFlagGreen = [  0/256 104/256 71/256];
  gray = [.4 .4 .4];
  ygain = 25 * overallGain;

  % 13 pixels between lines
  % side, feature type, label, ybaseline, ygain, color, linestyle
  % note that y = 0 is at the lower left
  ps  =[{'self'}, {'vo'}, {'Intensity'},  103+98, ygain, dustyPurple, {'-'}; ...  
	{'self'}, {'ph'}, {'Pitch Height'},103+85, ygain, gray, {'-'}; ...
	{'self'}, {'pr'}, {'Pitch Range'}, 103+72, ygain, gray, {'-'}; ...
	{'self'}, {'le'}, {'Lengthening'}, 103+59, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'cr'}, {'Creakiness'},  103+46, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'pd'}, {'Disalignment'},103+33, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'ap'}, {'Articu. Prec.'},103+20, ygain, gray, {'-'}; ...
		...
	{'inte'}, {'vo'}, {'Intensity'},  98 ygain, darkGreen, {'-'}; ...
	{'inte'}, {'ph'}, {'Pitch Height'},85, ygain, gray, {'-'}; ...
	{'inte'}, {'pr'}, {'Pitch Range'}, 72, ygain, gray, {'-'}; ...
	{'inte'}, {'le'}, {'Lengthening'}, 59, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'cr'}, {'Creakiness'},  46, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'pd'}, {'Disalignment'},33, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'ap'}, {'Articu. Prec.'},20, ygain, gray, {'-'}; ...
       ];
end
