function ps = pbookPlotspecCppsRedu(overallGain)

  dustyPurple = [130/256 96/256 176/256];    
  darkGreen  = [117/256 180/256 82/256];     
  mexicanFlagRed = [206/256  17/256  38/256]; 
  mexicanFlagGreen = [  0/256 104/256 71/256];
  gray = [.4 .4 .4];
  ygain = 25 * overallGain;

  % 13 pixels between lines
  % side, feature type, label, ybaseline, ygain, color, linestyle
  % note that y = 0 is at the lower left
  ps  =[{'self'}, {'hr'}, {'Hubert Redu'},  133+111, ygain, gray, {'-'}; ...  
	{'self'}, {'vo'}, {'Intensity'},  133+98, ygain, dustyPurple, {'-'}; ...  
	{'self'}, {'ph'}, {'Pitch Height'},133+85, ygain, gray, {'-'}; ...
	{'self'}, {'pr'}, {'Pitch Range'}, 133+72, ygain, gray, {'-'}; ...
	{'self'}, {'le'}, {'Lengthening'}, 133+59, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'cr'}, {'Creakiness'},  133+46, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'pd'}, {'Disalignment'},133+33, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'ap'}, {'Articu. Prec.'},133+20, ygain, gray, {'-'}; ...
	{'self'}, {'cp'}, {'CPPS.'},133+07, ygain, gray, {'-'}; ...
		...
	{'inte'}, {'hr'}, {'HubertRedu.'}, 114, ygain, gray, {'-'}; ...
	{'inte'}, {'vo'}, {'Intensity'},  101, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'ph'}, {'Pitch Height'},88, ygain, gray, {'-'}; ...
	{'inte'}, {'pr'}, {'Pitch Range'}, 75, ygain, gray, {'-'}; ...
	{'inte'}, {'le'}, {'Lengthening'}, 62, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'cr'}, {'Creakiness'},  49, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'pd'}, {'Disalignment'},36, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'ap'}, {'Articu. Prec.'},23, ygain, gray, {'-'}; ...
	{'inte'}, {'cp'}, {'CPPS.'}, 10, ygain, gray, {'-'}; ...
       ];
end
