% derived from pbookPlotspec; shows each feature, without combining near-opposites
function ps = uncompressedSpec(overallGain)

  dustyPurple = [130/256 96/256 176/256];    
  darkGreen  = [117/256 180/256 82/256];     
  mexicanFlagRed = [206/256  17/256  38/256]; 
  mexicanFlagGreen = [  0/256 104/256 71/256];
  gray = [.4 .4 .4];
  ygain = 25 * overallGain;

  % side, feature type, label, ybaseline, ygain, color, linestyle
  % note that y = 0 is at the lower left
  ps  =[{'self'}, {'vo'}, {'Intensity'},  215, ygain, dustyPurple, {'-'}; ...  
	{'self'}, {'th'}, {'P. Highness'},205, ygain, gray, {'-'}; ...
	{'self'}, {'tl'}, {'P. Lowness'},195, ygain, gray, {'-'}; ...
	{'self'}, {'wp'}, {'P. Wideness'}, 185, ygain, gray, {'-'}; ...
	{'self'}, {'np'}, {'P. Narrowness'}, 175, ygain, gray, {'-'}; ...
	{'self'}, {'le'}, {'Lengthening'}, 165, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'cr'}, {'Creakiness'},  155, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'pd'}, {'Disalignment'},145, ygain, dustyPurple, {'-'}; ...
	{'self'}, {'en'}, {'Enunciation'},135, ygain, gray, {'-'}; ...
	{'self'}, {'re'}, {'Reduction'},125, ygain, gray, {'-'}; ...
		...
	{'inte'}, {'vo'}, {'Intensity'},  110, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'th'}, {'P. Highness'},100, ygain, gray, {'-'}; ...
	{'inte'}, {'tl'}, {'P. Lowness'},90, ygain, gray, {'-'}; ...
	{'inte'}, {'wp'}, {'P. Wideness'}, 80, ygain, gray, {'-'}; ...
	{'inte'}, {'np'}, {'P. Narrowness'}, 70, ygain, gray, {'-'}; ...
	{'inte'}, {'le'}, {'Lengthening'}, 60, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'cr'}, {'Creakiness'},  50, ygain, gray, {'-'}; ...
	{'inte'}, {'pd'}, {'Disalignment'},40, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'en'}, {'Enunciation'},30, ygain, darkGreen, {'-'}; ...
	{'inte'}, {'re'}, {'Reduction'},  20, ygain, darkGreen, {'-'}; ...

       ];
end
